create table students (
    student_id number generated by default as identity primary key,
    first_name varchar2(50) not null,
    last_name varchar2(50) not null,
    email varchar2(100) not null unique
)
/

create table courses (
    course_id number generated by default as identity primary key,
    code varchar2(20) not null unique,
    title varchar2(200) not null
)
/

create table enrollments (
    student_id number not null,
    course_id number not null,
    enrolled_on date default sysdate not null,
    grade varchar2(2),
    constraint pk_enrollments primary key (student_id, course_id),
    constraint fk_enrl_student foreign key (student_id)
        references students(student_id),
    constraint fk_enrl_course foreign key (course_id)
        references courses(course_id)
)
/
