services:
  oracledb:
    image: gvenzl/oracle-free:23.26.1-slim-faststart
    container_name: oracledb
    ports:
      # container available on port 1521
      - 1521:1521
    environment:
      # sys password
      - ORACLE_PASSWORD=Welcome12345
    volumes:
      # any scripts in the "oracle" directory are run on db startup
      - ./oracle:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "lsnrctl status | grep READY"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s