drop table if exists ticket_chunks purge;
drop table if exists ticket_product_edges purge;
drop table if exists support_tickets purge;
drop table if exists runbooks purge;
drop table if exists customer_orders purge;
drop table if exists products purge;
drop table if exists customers purge;

-- customers: support accounts used by relational filters and graph impact traversal.
create table customers (
    customer_id number primary key,
    name varchar2(120) not null,
    tier varchar2(30) not null,
    region varchar2(40) not null
);

-- products: product catalog rows with JSON diagnostics that connect tickets, orders, search, and graph examples.
create table products (
    product_id number primary key,
    name varchar2(120) not null,
    specs json not null
);

-- customer_orders: operational order state used to constrain similar-ticket search and model customer-to-product graph edges.
create table customer_orders (
    order_id number primary key,
    customer_id number not null references customers(customer_id),
    product_id number not null references products(product_id),
    order_status varchar2(30) not null,
    opened_at timestamp default systimestamp not null
);

-- support_tickets: the main support workload table, combining relational ownership fields with JSON diagnostics.
create table support_tickets (
    ticket_id number generated by default on null as identity primary key,
    customer_id number not null references customers(customer_id),
    order_id number not null references customer_orders(order_id),
    product_id number not null references products(product_id),
    subject varchar2(200) not null,
    body clob not null,
    status varchar2(30) default 'OPEN' not null,
    sla_status varchar2(30) not null,
    payload json not null,
    created_at timestamp default systimestamp not null
);

-- runbooks: product-family troubleshooting content that enrichment turns into searchable vector chunks.
create table runbooks (
    runbook_id number primary key,
    product_family varchar2(60) not null,
    error_code varchar2(40) not null,
    title varchar2(200) not null,
    body clob not null
);

-- ticket_chunks: generated ticket and runbook text chunks with embeddings for vector similarity search.
create table ticket_chunks (
    chunk_id number generated always as identity primary key,
    ticket_id number not null references support_tickets(ticket_id) on delete cascade,
    chunk_type varchar2(30) not null,
    chunk_text clob not null,
    embedding vector(384, FLOAT32) annotations(Distance 'COSINE', IndexType 'IVF'),
    created_at timestamp default systimestamp not null
);

-- ticket_product_edges: explicit ticket-to-product relationships used by the SQL property graph.
create table ticket_product_edges (
    edge_id number generated always as identity primary key,
    ticket_id number not null references support_tickets(ticket_id) on delete cascade,
    product_id number not null references products(product_id),
    relationship varchar2(40) default 'AFFECTS' not null
);

-- customer_orders_customer_idx: supports order lookups by customer and operational status.
create index customer_orders_customer_idx on customer_orders(customer_id, order_status);

-- customer_orders_product_idx: supports product-scoped order lookups for graph and impact queries.
create index customer_orders_product_idx on customer_orders(product_id, order_status);

-- support_tickets_customer_idx: supports customer-tier and SLA filtered ticket search.
create index support_tickets_customer_idx on support_tickets(customer_id, sla_status);

-- support_tickets_product_idx: supports product and ticket-status filtering for support workflows.
create index support_tickets_product_idx on support_tickets(product_id, status);

-- support_tickets_payload_text_idx: Oracle Text JSON search index for matching ticket diagnostics, subjects, and bodies.
create search index support_tickets_payload_text_idx
on support_tickets (payload)
for json
parameters ('sync (on commit) search_on text include ($.ticketCode, $.errorCode, $.sku, $.subject, $.body)');

-- products_specs_text_idx: Oracle Text JSON search index for product SKU, family, and diagnostic metadata.
create search index products_specs_text_idx
on products (specs)
for json
parameters ('sync (on commit) search_on text include ($.sku, $.family, $.diagnostics)');

-- ticket_chunks_vector_idx: vector index used to rank ticket and runbook chunks by semantic similarity.
create vector index ticket_chunks_vector_idx
on ticket_chunks (embedding)
organization neighbor partitions
distance COSINE
with target accuracy 95
parameters (type IVF, neighbor partitions 4);

-- support_ticket_graph: property graph that connects customers, tickets, products, and orders for impact analysis.
create property graph support_ticket_graph
vertex tables (
    customers
        key (customer_id)
        label customer
        properties (customer_id, name, tier, region),
    products
        key (product_id)
        label product
        properties (product_id, name),
    support_tickets
        key (ticket_id)
        label ticket
        properties (ticket_id, subject, status, sla_status)
)
edge tables (
    ticket_product_edges
        key (edge_id)
        source key (ticket_id) references support_tickets(ticket_id)
        destination key (product_id) references products(product_id)
        label affects
        properties (edge_id, relationship),
    customer_orders
        key (order_id)
        source key (customer_id) references customers(customer_id)
        destination key (product_id) references products(product_id)
        label bought
        properties (order_id, order_status)
);

-- tickets_dv: JSON Relational Duality View that exposes each support ticket as a nested document.
create or replace force editionable json relational duality view tickets_dv as
support_tickets @insert @update @delete {
    _id : ticket_id
    subject
    body
    status
    slaStatus : sla_status
    createdAt : created_at
    diagnostics : payload
    customer : customers {
        _id : customer_id
        name
        tier
        region
    }
    product : products {
        _id : product_id
        name
        specs
    }
    order : customer_orders {
        _id : order_id
        orderStatus : order_status
        openedAt : opened_at
    }
};
