services:

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
  free23ai:
    image: gvenzl/oracle-free:23.9-slim-faststart
    container_name: free23ai
    ports:
      - 1522:1521
    environment:
      - ORACLE_PASSWORD=Welcome12345
    volumes:
      - ./oracle:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "lsnrctl status | grep READY"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s