<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.example</groupId>
        <artifactId>oracle-database-java-samples</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>spring-boot-jdbc-tracing</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>spring-boot-jdbc-custom-tracer</name>
    <description>Implement a custom JDBC tracer with Oracle AI Database</description>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.oracle.database.spring</groupId>
            <artifactId>oracle-spring-boot-starter-ucp</artifactId>
            <version>${oracle.starters.version}</version>
        </dependency>

        <!-- Observability / Tracing is implemented in Actuator. -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <!-- Tracing library. -->
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-otel</artifactId>
        </dependency>
        <!-- Report traces to Zipkin -->
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-exporter-zipkin</artifactId>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>net.ttddyy.observation</groupId>-->
<!--            <artifactId>datasource-micrometer-spring-boot</artifactId>-->
<!--            <version>1.0.2</version>-->
<!--        </dependency>-->

        <!-- Include if using Oracle Database Wallet -->
<!--        <dependency>-->
<!--            <groupId>com.oracle.database.spring</groupId>-->
<!--            <artifactId>oracle-spring-boot-starter-wallet</artifactId>-->
<!--            <version>${oracle.version}</version>-->
<!--        </dependency>-->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.example.tracing.jdbc.JDBCTracingApp</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
