CREATE TABLE IF NOT EXISTS LANGCHAIN_RUNBOOK_SOURCES (
    runbook_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(120) NOT NULL,
    product VARCHAR2(40) NOT NULL,
    severity VARCHAR2(20) NOT NULL,
    body CLOB NOT NULL
)
/
INSERT ALL
    INTO LANGCHAIN_RUNBOOK_SOURCES (runbook_id, title, product, severity, body)
    VALUES (
        101,
        'Stabilize VPN over Wi-Fi',
        'network',
        'high',
        q'[Use this runbook when a VPN client disconnects every few minutes on Wi-Fi but stays connected on Ethernet. Verify the wireless adapter driver, disable Wi-Fi power saving, upgrade or reinstall the VPN client, collect client logs, and confirm the tunnel stays connected for fifteen minutes before closing the incident.]'
    )
    INTO LANGCHAIN_RUNBOOK_SOURCES (runbook_id, title, product, severity, body)
    VALUES (
        102,
        'Reset MFA and password lockouts',
        'identity',
        'medium',
        q'[Use this runbook when a user cannot sign in because the account is locked, the password expired, or MFA push notifications stopped. Verify identity, clear the lockout, reset the password when needed, re-register the MFA device, and ask the user to complete a fresh sign-in before closing the ticket.]'
    )
    INTO LANGCHAIN_RUNBOOK_SOURCES (runbook_id, title, product, severity, body)
    VALUES (
        103,
        'Repair PDF upload failures',
        'documents',
        'medium',
        q'[Use this runbook when a document portal rejects PDF upload requests or shows validation errors after a browser update. Clear the browser cache, check file size and MIME type, reinstall the desktop helper if present, retry the upload workflow, and capture the request identifier for engineering when the failure repeats.]'
    )
    INTO LANGCHAIN_RUNBOOK_SOURCES (runbook_id, title, product, severity, body)
    VALUES (
        104,
        'Choose storage for analytics exports',
        'storage',
        'low',
        q'[Use this runbook when a team asks whether analytics exports belong in object storage or block storage. Compare access pattern, retention policy, throughput needs, lifecycle rules, and restore expectations, then document the storage decision and link to the internal cost review before implementation.]'
    )
SELECT 1 FROM dual
/
COMMIT
/
CREATE INDEX langchain_runbook_text_idx
    ON "langchain_runbook_chunks" (text)
    INDEXTYPE IS CTXSYS.CONTEXT
    PARAMETERS ('SYNC (ON COMMIT)')
/
