drop table if exists json_inventory purge;

create table json_inventory (
    product_id number generated by default on null as identity primary key,
    product_doc json not null
);

-- Optimizes membership checks for numeric values in the compatiblePartIds array.
-- Each product can contribute several part IDs to the index.
create multivalue index product_parts_mvi
on json_inventory i (i.product_doc.compatiblePartIds.numberOnly());

-- Optimizes region lookups across warehouse objects nested in each product.
-- Each product can be indexed once per stocked warehouse region.
create multivalue index product_regions_mvi
on json_inventory i (i.product_doc.warehouses.region.stringOnly());

-- Optimizes component searches that match type and partId from the same array item.
-- The json_table expression keeps related component fields together in one composite index entry.
create multivalue index product_components_mvi
on json_inventory
(json_table(product_doc, '$.components[*]'
    error on error null on empty null on mismatch
    columns (
        componentType varchar2(30) path '$.type',
        componentPart number(10) path '$.partId'
    )));
