spring:
  datasource:
    username: ${USERNAME:testuser}
    password: ${PASSWORD:testpwd}
    url: ${JDBC_URL:jdbc:oracle:thin:@localhost:1521/freepdb1}

    # Set these to use UCP over Hikari.
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      initial-pool-size: 1
      min-pool-size: 1
      max-pool-size: 30
      connection-pool-name: DefaultConnectionPool
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
logging:
  level:
    root: error
