[project]
name = "python-oracle"
version = "0.1.0"
description = ""
authors = [
    {name = "Anders Swanson",email = "anders.swanson@oracle.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    # Oracle thin driver
    "oracledb (>=26.0.0)",

    # Run Oracle containers locally
    "testcontainers (>=4.15.0)",

    # Load hook configuration
    "pyyaml (>=6.0.3,<7.0.0)",

    # LangChain
    "langchain (==1.4.1)",
    "langchain-oracledb (>=1.5.0,<2.0.0)",
    "langchain-openai (>=1.6.2,<2.0.0)",
    "langchain-community (>=0.4.2,<0.5.0)",
    "langchain-mcp-adapters (>=0.3.2,<1.0.0)",
    "langgraph (>=1.2.11,<2.0.0)",
    "langgraph-oracledb (>=1.0.1,<2.0.0)",
    "langchain-oci (>=0.3.2,<1.0.0)",
    "pymongo (>=4.18.1,<5.0.0)",
    "sentence-transformers (>=6.0.1,<7.0.0)"
]

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["src*"]
