[project]
name = "python-oracle"
version = "0.1.0"
description = ""
authors = [
    {name = "Anders Swanson",email = "anders.swanson@oracle.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    # Oracle thin driver
    "oracledb (>=3.4.2)",

    # Run Oracle containers locally
    "testcontainers (>=4.14.1)",

    # LangChain
    "langchain-oracledb (>=1.2.0,<2.0.0)",
    "langchain-openai (>=1.1.7,<2.0.0)",
    "langchain-community (>=0.4.1,<0.5.0)"
]

[tool.poetry]
packages = [
    { include = "src/" },
    { include = "src/**/*.py" },
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
