# Load sample kitchen-sink workflow
loadSample=false

# Security settings
conductor.security.enabled=false

# Workflow Engine context
server.servlet.context-path=/workflow-server

# Conductor secrets encryption key file path
conductor.secrets.encryption.keypath=/run/secrets/WF_ENCRYPTION_KEY

# Oracle AI Database persistence
conductor.db.type=oracle
conductor.queue.type=oracle

# Oracle AI Database connectivity
spring.datasource.url=jdbc:oracle:thin:@//microtxdb:1521/FREEPDB1
spring.datasource.username=microtx
spring.datasource.password=Welcome12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
conductor.oracle.flyway-enabled=true

# Indexing properties
conductor.indexing.enabled=true
conductor.indexing.type=oracle
# Required to disable connecting to Elasticsearch.
conductor.elasticsearch.version=0

# Additional modules for metrics collection exposed to Prometheus (optional)
conductor.metrics-prometheus.enabled=true
management.endpoints.web.exposure.include=prometheus

# Callback URL for the coordinator
conductor.tasks.microtx.participantCallbackUrl=http://workflow-server:9010/workflow-server

# Enable TxEventQ event handler
# conductor.event-queues.txeventq.enabled=true

# Default event queue type
# conductor.default-event-queue.type=txeventq

# Maximum number of messages to poll
# conductor.event-queues.txeventq.max-batch=10

# Maximum number of parallel threads for the event processor
# conductor.app.event-processor-thread-count=5
